### ISSUE TITLE
3.1 Create a REST api endpoint for deleting a review

### ISSUE THREAD

**Issue by Jukalekvi** [Team-417-Expectation-Failed/QuizzerApp#111]
Idea logic:
After the review entity has been created we want to create the endpoint to delete a review. 

Code logic:
We need to create controller logic handle the requests to delete correctly. We need to make sure we have the right quiz id and the right review id. The business logic to delete the right review for the quiz it relates to resides in the service layer, but I think we also need to pass the quiz id and review id to the business logic.

**Comment by juusokarjanlahti** [comment]
After the review entity has been created we want to create the endpoint to delete a review. 

To do this we need to create controller logic handle the requests to delete correctly. We need to make sure we have the right quiz id and the right review id. The business logic to delete the right review for the quiz it relates to resides in the service layer, but I think we also need to pass the quiz id and review id to the business logic.
