### ISSUE TITLE
Implement a REST API endpoint for getting all the anwers (submitted by the students) of a quiz. (Exercise 14, sprint 2)

### ISSUE THREAD

**Issue by helikulomaa** [Team-417-Expectation-Failed/QuizzerApp#119]

**Comment by juusokarjanlahti** [comment]
Created getAnswersByQuizId that should work. 

It's stuck in the cleanup-branch thought and needs to be merged back to the main branch.

Answer entity
![Image](https://github.com/user-attachments/assets/dbd46b61-9fb3-47ae-bacf-a819eca1ae89)
AnswerOption entity
![Image](https://github.com/user-attachments/assets/b5309ba9-4f41-4fda-b74d-5aab0ca45992)
Question entity
![Image](https://github.com/user-attachments/assets/ae5f9581-19eb-4e08-920e-d26227bc1ab5)
getAnswersByQuizId controller method
![Image](https://github.com/user-attachments/assets/bf7483ff-65ca-4fd6-9e4f-0774f639b7b9)
Testdata Create answers
![Image](https://github.com/user-attachments/assets/b70dab3d-c2d3-4ecf-904f-b89ca20b24e4)
