### ISSUE TITLE
As a teacher, I want to add an answer option to a question so that students can learn about course-related topics

### ISSUE THREAD

**Issue by helikulomaa** [Team-417-Expectation-Failed/QuizzerApp#8]

**Comment by kuxacodes** [comment]
Can someone try to break this down to smaller tasks?

**Comment by helikulomaa** [comment]
I think the tasks are already there. Here's my understanding of the needed tasks: 
1.	adding an answer option to a question
2.	listing a question’s answer options
3.	editing an answer option
4.	deleting an answer option
