### ISSUE TITLE
As a teacher, I want to see a list of questions’s answer options so that I know which answer options the question has

### ISSUE THREAD

**Issue by helikulomaa** [Team-417-Expectation-Failed/QuizzerApp#9]

**Comment by kuxacodes** [comment]
How can  a multiple choice question have multiple answer options?

Question -> Answer (multiple)
One To Many
Return questions all answers (if any)

**Comment by helikulomaa** [comment]
Not sure I understand your question, but the question has multiple answer options and one of them is correct.
